[workspace]

members = [
'xen-core', # Xen core
'xen-pbr', # Xen Renderer
'xen-loop', # Xen Gameloop
'xen-input', # Keyboard/Mouse/VR Input library
'spatial',  # Spatial Audio library for xen
'openxr'
]
